<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'SynergyGearman\Job\AbstractJob'                    => __DIR__ . '/src/SynergyGearman/Job/AbstractJob.php',
    'SynergyGearman\Job\Pecl'                           => __DIR__ . '/src/SynergyGearman/Job/Pecl.php',
    'SynergyGearman\Exception'                          => __DIR__ . '/src/SynergyGearman/Exception.php',
    'SynergyGearman\Exception\InvalidArgumentException' => __DIR__ . '/src/SynergyGearman/Exception/InvalidArgumentException.php',
    'SynergyGearman\Exception\RuntimeException'         => __DIR__ . '/src/SynergyGearman/Exception/RuntimeException.php',
    'SynergyGearman\Exception\DomainException'          => __DIR__ . '/src/SynergyGearman/Exception/DomainException.php',
    'SynergyGearman\Worker\Pecl'                        => __DIR__ . '/src/SynergyGearman/Worker/Pecl.php',
    'SynergyGearman\Client\Pecl'                        => __DIR__ . '/src/SynergyGearman/Client/Pecl.php',
    'SynergyGearman\Connection\AbstractPecl'            => __DIR__ . '/src/SynergyGearman/Connection/AbstractPecl.php',
    'SynergyGearman\ClientInterface'                    => __DIR__ . '/src/SynergyGearman/ClientInterface.php',
    'SynergyGearman\TaskInterface'                      => __DIR__ . '/src/SynergyGearman/TaskInterface.php',
    'SynergyGearman\ConnectionInterface'                => __DIR__ . '/src/SynergyGearman/ConnectionInterface.php',
    'SynergyGearman\Task\Task'                          => __DIR__ . '/src/SynergyGearman/Task/Task.php',
    'SynergyGearman\JobInterface'                       => __DIR__ . '/src/SynergyGearman/JobInterface.php',
    'SynergyGearman\WorkerInterface'                    => __DIR__ . '/src/SynergyGearman/WorkerInterface.php',
    'SynergyGearman\Module'                             => __DIR__ . '/Module.php',
);